"""Replay a NeuroSym counterexample through the real, compiled program.

ESBMC's own symbolic trace-walker can report a bogus source location for a
sat verdict when it has to derive a value NeuroSym's flat model does not
cover (an array index, a pointer dereference) -- it falls back to a
placeholder rather than the real value, and the reconstructed trace can
walk a different path through the program than the one that actually
triggers the bug. This tool sidesteps that entirely: it pulls the ordered
sequence of nondet input values straight out of NeuroSym's own model, feeds
that exact sequence into the real source file compiled normally, and lets
libc's own assert()/signal reporting give the true crash location from a
real execution -- no symbolic reconstruction involved.

Stubs every nondet/verification builtin ESBMC's frontend declares (see
internal_additions() in src/clang-c-frontend/clang_c_language.cpp) -- both
naming conventions (nondet_TYPE and the SV-COMP __VERIFIER_nondet_TYPE
forms) share one call-ordered value sequence, since ESBMC allocates one
nondet$symex::nondetN symbol per call regardless of which builtin name was
used. __VERIFIER_error() is treated the same as reaching assert(0): it
aborts, so a real execution reaching it is reported the same way. Only
meaningful for programs whose behaviour is fully determined by these
builtins (the RERS/SV-COMP harness pattern this was built against) -- any
other source of nondeterminism ESBMC models internally (uninitialized
memory, threads) will not be reproduced.

Usage:
    python3 -m gansat.ns_concretize MODEL_OUTPUT.txt SOURCE.c [-o OUT.c]

MODEL_OUTPUT.txt is NeuroSym's raw stdout on a sat formula (containing the
"(model (define-fun nondet$symex::nondetN () SORT VALUE) ...)" block
ESBMC's neurosym backend already parses -- see
src/solvers/neurosym/neurosym_conv.cpp in the ESBMC tree). SORT is
"(_ BitVec N)" or "Bool"; other sorts (floating-point) are not currently
decoded and fall back to 0, same as an unrecognized entry.
"""

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# "(_ BitVec N) VALUE" or "Bool VALUE" -- the two sorts NeuroSym's own
# format_output() emits for scalar nondets (see gansat/ns_solver.py).
NONDET_RE = re.compile(
    r"define-fun nondet\$symex::nondet(\d+) \(\) "
    r"(?:\(_ BitVec (\d+)\) (#x[0-9a-fA-F]+|#b[01]+)|Bool (true|false))"
)

# name -> (C return type, bit width used to mask/truncate the raw value).
# Mirrors the forward declarations in internal_additions()
# (src/clang-c-frontend/clang_c_language.cpp) exactly, both naming
# conventions -- every entry pulls from the same shared sequence, since
# ESBMC does not distinguish them at the nondet-symbol level.
NONDET_BUILTINS = {
    "int": 32,
    "uint": 32,
    "long": 64,
    "ulong": 64,
    "short": 16,
    "ushort": 16,
    "char": 8,
    "uchar": 8,
    "schar": 8,
    "bool": 1,
}
NONDET_C_TYPE = {
    "int": "int",
    "uint": "unsigned int",
    "long": "long",
    "ulong": "unsigned long",
    "short": "short",
    "ushort": "unsigned short",
    "char": "char",
    "uchar": "unsigned char",
    "schar": "signed char",
    "bool": "_Bool",
}

HARNESS_PREAMBLE = """\
/* Auto-generated by ns_concretize.py: replays NeuroSym's own counterexample
 * nondet sequence through the real program so the crash location comes
 * from genuine execution, not ESBMC's symbolic trace-walker. */
#include <stdio.h>
#include <stdlib.h>

static const unsigned long long __nondet_seq[] = {{
  {values}
}};
static int __nondet_idx = 0;

static unsigned long long __nondet_next(void)
{{
  if (__nondet_idx >= (int)(sizeof(__nondet_seq) / sizeof(__nondet_seq[0])))
  {{
    fprintf(stderr, "[ns_concretize] ran out of recorded nondet values at "
                     "index %d without hitting the bug -- real execution "
                     "diverged from the model\\n", __nondet_idx);
    return 0;
  }}
  return __nondet_seq[__nondet_idx++];
}}

{stubs}
#define __CPROVER_input(name, val) ((void)0)
#define __CPROVER_assume(cond) ((void)0)
#define __VERIFIER_assume(cond) ((void)0)
#define __VERIFIER_atomic_begin() ((void)0)
#define __VERIFIER_atomic_end() ((void)0)

static void __VERIFIER_error(void)
{{
  fprintf(stderr, "[ns_concretize] __VERIFIER_error() reached\\n");
  abort();
}}

"""

STUB_TEMPLATE = """\
static {ctype} nondet_{suffix}(void) {{ return ({ctype})__nondet_next(); }}
static {ctype} __VERIFIER_nondet_{suffix}(void) {{ return ({ctype})__nondet_next(); }}
"""


def parse_nondet_sequence(model_output: str) -> list[int]:
    """Extract the free-variable input sequence in call order.

    ESBMC numbers nondet$symex::nondetN sequentially as symex encounters
    each nondet call, so sorting by N recovers call order. Values after the
    one that actually triggers the bug are typically unconstrained (the
    formula does not care what they are, since that code path is never
    reached) and can be nonsensical -- harmless, since real execution stops
    at the true crash before reaching them. Stored as raw unsigned bit
    patterns; the generated stub for each builtin casts to its own C type,
    so a value recorded against a narrower sort (e.g. nondet_char, an
    8-bit BitVec) still truncates correctly regardless of which builtin
    ends up consuming it.
    """
    pairs = []
    for m in NONDET_RE.finditer(model_output):
        idx = int(m.group(1))
        if m.group(4) is not None:  # Bool sort
            val = 1 if m.group(4) == "true" else 0
        else:
            raw = m.group(3)
            val = int(raw[2:], 16) if raw.startswith("#x") else int(raw[2:], 2)
        pairs.append((idx, val))
    pairs.sort(key=lambda p: p[0])
    return [v for _, v in pairs]


def build_harness(source: str, values: list[int]) -> str:
    body = ",\n  ".join(str(v) for v in values)
    stubs = "".join(
        STUB_TEMPLATE.format(ctype=NONDET_C_TYPE[suffix], suffix=suffix)
        for suffix in NONDET_BUILTINS
    )
    return HARNESS_PREAMBLE.format(values=body, stubs=stubs) + source


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("model_output", help="NeuroSym's raw stdout on a sat run")
    ap.add_argument("source", help="the original C source file")
    ap.add_argument(
        "-o", "--out", help="where to write the generated harness (default: temp file)"
    )
    ap.add_argument(
        "--cc", default="gcc", help="C compiler to use (default: gcc)"
    )
    args = ap.parse_args()

    model_output = Path(args.model_output).read_text(errors="replace")
    values = parse_nondet_sequence(model_output)
    if not values:
        print(
            "no nondet$symex::nondetN entries found in the model output -- "
            "nothing to replay",
            file=sys.stderr,
        )
        return 1
    print(f"parsed {len(values)} nondet input values, first 10: {values[:10]}")
    sys.stdout.flush()  # print before the child process's own stderr output

    source = Path(args.source).read_text(errors="replace")
    harness = build_harness(source, values)

    out_path = Path(args.out) if args.out else None
    with tempfile.TemporaryDirectory() as tmp:
        harness_c = out_path or Path(tmp) / "harness.c"
        harness_c.write_text(harness)
        harness_bin = Path(tmp) / "harness"

        compile_res = subprocess.run(
            [args.cc, "-g", "-o", str(harness_bin), str(harness_c)],
            capture_output=True,
            text=True,
        )
        if compile_res.returncode != 0:
            print(compile_res.stderr, file=sys.stderr)
            return compile_res.returncode

        run_res = subprocess.run(
            [str(harness_bin)], capture_output=True, text=True
        )
        # stdout is line-buffered/block-buffered while stderr is not, so
        # printing to both in this order can still interleave out of order
        # on the terminal -- flush stdout right after so it lands first.
        print(run_res.stdout, end="")
        sys.stdout.flush()
        print(run_res.stderr, end="", file=sys.stderr)

        if run_res.returncode == 0:
            print(
                "\n[ns_concretize] program ran to completion without "
                "crashing -- the recorded sequence did not reproduce the "
                "bug (stale model vs. source mismatch, or a nondeterminism "
                "source outside the stubbed builtins)"
            )
        else:
            print(
                f"\n[ns_concretize] program terminated abnormally "
                f"(exit code {run_res.returncode}); the message above "
                f"(if any) names the real file:line -- ground truth from "
                f"actual execution, independent of ESBMC's trace-walker"
            )
        return 0


if __name__ == "__main__":
    sys.exit(main())
