"""Replay a NeuroSym counterexample through the real, compiled program.

ESBMC's own symbolic trace-walker can report a bogus source location for a
sat verdict when it has to derive a value NeuroSym's flat model does not
cover (an array index, a pointer dereference) -- it falls back to a
placeholder rather than the real value, and the reconstructed trace can
walk a different path through the program than the one that actually
triggers the bug. This tool sidesteps that entirely: it pulls the ordered
sequence of nondet input values straight out of NeuroSym's own model, feeds
that exact sequence into the real source file compiled normally, and lets
libc's own assert()/signal reporting give the true crash location from a
real execution -- no symbolic reconstruction involved.

Only meaningful for programs whose behaviour is fully determined by a
sequence of __VERIFIER_nondet_int()/nondet_int() calls (the RERS reachability
benchmark pattern this was built against) -- any other source of
nondeterminism ESBMC models internally (uninitialized memory, threads) will
not be reproduced.

Usage:
    python3 -m gansat.ns_concretize MODEL_OUTPUT.txt SOURCE.c [-o OUT.c]

MODEL_OUTPUT.txt is NeuroSym's raw stdout on a sat formula (containing the
"(model (define-fun nondet$symex::nondetN () (_ BitVec 32) VALUE) ...)"
block ESBMC's neurosym backend already parses -- see
src/solvers/neurosym/neurosym_conv.cpp in the ESBMC tree).
"""

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

NONDET_RE = re.compile(
    r"define-fun nondet\$symex::nondet(\d+) \(\) \(_ BitVec 32\) "
    r"(#x[0-9a-fA-F]+|#b[01]+)"
)

HARNESS_PREAMBLE = """\
/* Auto-generated by ns_concretize.py: replays NeuroSym's own counterexample
 * nondet sequence through the real program so the crash location comes
 * from genuine execution, not ESBMC's symbolic trace-walker. */
#include <stdio.h>

static const int __nondet_seq[] = {{
  {values}
}};
static int __nondet_idx = 0;

static int nondet_int(void)
{{
  if (__nondet_idx >= (int)(sizeof(__nondet_seq) / sizeof(__nondet_seq[0])))
  {{
    fprintf(stderr, "[ns_concretize] ran out of recorded nondet values at "
                     "index %d without hitting the bug -- real execution "
                     "diverged from the model\\n", __nondet_idx);
    return 0;
  }}
  return __nondet_seq[__nondet_idx++];
}}

#define __CPROVER_input(name, val) ((void)0)

"""


def parse_nondet_sequence(model_output: str) -> list[int]:
    """Extract the free-variable input sequence in call order.

    ESBMC numbers nondet$symex::nondetN sequentially as symex encounters
    each nondet_int() call, so sorting by N recovers call order. Values
    after the one that actually triggers the bug are typically
    unconstrained (the formula does not care what they are, since that
    code path is never reached) and can be nonsensical -- harmless, since
    real execution stops at the true crash before reaching them.
    """
    pairs = []
    for m in NONDET_RE.finditer(model_output):
        idx = int(m.group(1))
        raw = m.group(2)
        val = int(raw[2:], 16) if raw.startswith("#x") else int(raw[2:], 2)
        if val >= 2**31:  # reinterpret as signed 32-bit, matching C `int`
            val -= 2**32
        pairs.append((idx, val))
    pairs.sort(key=lambda p: p[0])
    return [v for _, v in pairs]


def build_harness(source: str, values: list[int]) -> str:
    body = ",\n  ".join(str(v) for v in values)
    return HARNESS_PREAMBLE.format(values=body) + source


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("model_output", help="NeuroSym's raw stdout on a sat run")
    ap.add_argument("source", help="the original C source file")
    ap.add_argument(
        "-o", "--out", help="where to write the generated harness (default: temp file)"
    )
    ap.add_argument(
        "--cc", default="gcc", help="C compiler to use (default: gcc)"
    )
    args = ap.parse_args()

    model_output = Path(args.model_output).read_text(errors="replace")
    values = parse_nondet_sequence(model_output)
    if not values:
        print(
            "no nondet$symex::nondetN entries found in the model output -- "
            "nothing to replay",
            file=sys.stderr,
        )
        return 1
    print(f"parsed {len(values)} nondet input values, first 10: {values[:10]}")
    sys.stdout.flush()  # print before the child process's own stderr output

    source = Path(args.source).read_text(errors="replace")
    harness = build_harness(source, values)

    out_path = Path(args.out) if args.out else None
    with tempfile.TemporaryDirectory() as tmp:
        harness_c = out_path or Path(tmp) / "harness.c"
        harness_c.write_text(harness)
        harness_bin = Path(tmp) / "harness"

        compile_res = subprocess.run(
            [args.cc, "-g", "-o", str(harness_bin), str(harness_c)],
            capture_output=True,
            text=True,
        )
        if compile_res.returncode != 0:
            print(compile_res.stderr, file=sys.stderr)
            return compile_res.returncode

        run_res = subprocess.run(
            [str(harness_bin)], capture_output=True, text=True
        )
        # stdout is line-buffered/block-buffered while stderr is not, so
        # printing to both in this order can still interleave out of order
        # on the terminal -- flush stdout right after so it lands first.
        print(run_res.stdout, end="")
        sys.stdout.flush()
        print(run_res.stderr, end="", file=sys.stderr)

        if run_res.returncode == 0:
            print(
                "\n[ns_concretize] program ran to completion without "
                "crashing -- the recorded sequence did not reproduce the "
                "bug (stale model vs. source mismatch, or a nondeterminism "
                "source outside plain nondet_int() calls)"
            )
        else:
            print(
                f"\n[ns_concretize] program terminated abnormally "
                f"(exit code {run_res.returncode}); the message above "
                f"(if any) names the real file:line -- ground truth from "
                f"actual execution, independent of ESBMC's trace-walker"
            )
        return 0


if __name__ == "__main__":
    sys.exit(main())
